name: CHeck API changes in java files

on:
  push:
    paths: 
    - '**.java'
    branches: [develop, uat, main, master]
       

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # compare with the previous commit

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygit2

      - name: Check for API annotations
        run: |
          python .github/workflows/check_api_changes.py